[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_filter_get_message_with_150_kb_payload with id: 2024-12-04_11-44-46__a16124d0-b32c-4b2d-ab55-8f365a7ce90a
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:34 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-12-04_11-44-46__a16124d0-b32c-4b2d-ab55-8f365a7ce90a__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.9.121
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['61577', '61578', '61579', '61580', '61581']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 61577:61577 -p 61578:61578 -p 61579:61579 -p 61580:61580 -p 61581:61581 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=61579 --rest-port=61577 --tcp-port=61578 --discv5-udp-port=61580 --rest-address=0.0.0.0 --nat=extip:172.18.9.121 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=fc8f018dfffd9a49ac6073e0240bfaba324ca3da48d4d75ea52af9d3fe2f8c1a --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=61581 --metrics-logging=true --relay=true --filter=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.9.121 waku 119159276f4f8ede3f4aa039082e37e67e2c03f528b788d08cad8f4524340eb0
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 119159276f4f. Setting up logs at ./log/docker/node1_2024-12-04_11-44-46__a16124d0-b32c-4b2d-ab55-8f365a7ce90a__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 61577
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:61577/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:61577/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.9.121/tcp/61578/p2p/16Uiu2HAmV7nSLxwbYkGjDtZECKZ8nB5jhtZxLfAmjNoTDE72kphB","/ip4/172.18.9.121/tcp/61579/ws/p2p/16Uiu2HAmV7nSLxwbYkGjDtZECKZ8nB5jhtZxLfAmjNoTDE72kphB"],"enrUri":"enr:-L24QLsVna_JL1-voMAR0Opml1u4ZlKczDbWixN3GytP04ciWLFTSswgfL3KAcfqG3rw-9Iv-GECMb9i3IXIYe_92h4CgmlkgnY0gmlwhKwSCXmKbXVsdGlhZGRyc5YACASsEgl5BvCKAAoErBIJeQbwi90DgnJzhQADAQAAiXNlY3AyNTZrMaED9Jgz6PBbESWaBnGi_ksndLlmY4oXZSXLljkBqMze_36DdGNwgvCKg3VkcILwjIV3YWt1MgU"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:39 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-12-04_11-44-46__a16124d0-b32c-4b2d-ab55-8f365a7ce90a__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.7.140
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['29469', '29470', '29471', '29472', '29473']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 29469:29469 -p 29470:29470 -p 29471:29471 -p 29472:29472 -p 29473:29473 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=29471 --rest-port=29469 --tcp-port=29470 --discv5-udp-port=29472 --rest-address=0.0.0.0 --nat=extip:172.18.7.140 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=abea22221db6dc3d16a31dceb8d7caac077ac73cb672c4790b152faeab13efa1 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=29473 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-L24QLsVna_JL1-voMAR0Opml1u4ZlKczDbWixN3GytP04ciWLFTSswgfL3KAcfqG3rw-9Iv-GECMb9i3IXIYe_92h4CgmlkgnY0gmlwhKwSCXmKbXVsdGlhZGRyc5YACASsEgl5BvCKAAoErBIJeQbwi90DgnJzhQADAQAAiXNlY3AyNTZrMaED9Jgz6PBbESWaBnGi_ksndLlmY4oXZSXLljkBqMze_36DdGNwgvCKg3VkcILwjIV3YWt1MgU --filternode=/ip4/172.18.9.121/tcp/61578/p2p/16Uiu2HAmV7nSLxwbYkGjDtZECKZ8nB5jhtZxLfAmjNoTDE72kphB
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.7.140 waku 82ff872c39b4ef49a181a14dd4caeb059865c2b0501b14c998999d18f40bbecc
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 82ff872c39b4. Setting up logs at ./log/docker/node2_2024-12-04_11-44-46__a16124d0-b32c-4b2d-ab55-8f365a7ce90a__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 29469
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:29469/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:29469/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.7.140/tcp/29470/p2p/16Uiu2HAkwUWhvb1c8eyJaAmaCZPoTefq6Nf8JWwpa79c9EBfEHr2","/ip4/172.18.7.140/tcp/29471/ws/p2p/16Uiu2HAkwUWhvb1c8eyJaAmaCZPoTefq6Nf8JWwpa79c9EBfEHr2"],"enrUri":"enr:-L24QJ-_g32Vwm6qMCl3L9hDClZY7ifDst6Ik-ZC92FWOGcFTIwAse_VQaNwJDapRLemek6YeRHT7ZoRSP1e0ila3kkCgmlkgnY0gmlwhKwSB4yKbXVsdGlhZGRyc5YACASsEgeMBnMeAAoErBIHjAZzH90DgnJzhQADAQAAiXNlY3AyNTZrMaECHnGhbibVwPnQH2A7I06liE4_YTNx2hYMj4PzCiNW4kODdGNwgnMeg3VkcIJzIIV3YWt1MgA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29469/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.9.121/tcp/61578/p2p/16Uiu2HAmV7nSLxwbYkGjDtZECKZ8nB5jhtZxLfAmjNoTDE72kphB"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.filter:filter.py:47 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:61577/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:29469/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "6a91354f-2222-478b-979e-33b1b6db98f2", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"6a91354f-2222-478b-979e-33b1b6db98f2","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:custom_logger.py:10 Log line was discarded because it's longer than max_log_line_length=5000
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 2 seconds
[35mDEBUG   [0m src.steps.filter:filter.py:98 Checking that peer NODE_2:wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:29469/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:custom_logger.py:10 Log line was discarded because it's longer than max_log_line_length=5000
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 119159276f4f
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 82ff872c39b4
[1m[31mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 119159276f4f. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.