[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_filter_get_message_with_extra_field with id: 2024-12-04_11-44-47__40c67114-19a2-49f1-8286-f62937734b76
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:34 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-12-04_11-44-47__40c67114-19a2-49f1-8286-f62937734b76__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.170.163
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['25309', '25310', '25311', '25312', '25313']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 25309:25309 -p 25310:25310 -p 25311:25311 -p 25312:25312 -p 25313:25313 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=25311 --rest-port=25309 --tcp-port=25310 --discv5-udp-port=25312 --rest-address=0.0.0.0 --nat=extip:172.18.170.163 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=dce0dd1f03b042bcca3bb3129fb141ebdca6c99cf6cc54a69df87ef039ccd7aa --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=25313 --metrics-logging=true --relay=true --filter=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.170.163 waku 01d2cffe58ef0d3df9083e6fe941cae5dceb85e948305f70facede342732111c
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 01d2cffe58ef. Setting up logs at ./log/docker/node1_2024-12-04_11-44-47__40c67114-19a2-49f1-8286-f62937734b76__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 25309
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:25309/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:25309/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.170.163/tcp/25310/p2p/16Uiu2HAmURzmvKJQbjssaJMaysSwpsM9wYFzUfUnDvrFexbJaDjy","/ip4/172.18.170.163/tcp/25311/ws/p2p/16Uiu2HAmURzmvKJQbjssaJMaysSwpsM9wYFzUfUnDvrFexbJaDjy"],"enrUri":"enr:-L24QEjj4xUxlXV9IV_vqY-uBRMLfDFxj9kNin8rV-1H1GBDAyxqgNTOOHXiZeR0b-1s7VFLrn65RqSVd7oRDrAaNhcCgmlkgnY0gmlwhKwSqqOKbXVsdGlhZGRyc5YACASsEqqjBmLeAAoErBKqowZi390DgnJzhQADAQAAiXNlY3AyNTZrMaED6mbro6vj87BxPWShMFyL9JfEoqijA96XJiHeD8O5DCSDdGNwgmLeg3VkcIJi4IV3YWt1MgU"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:39 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-12-04_11-44-47__40c67114-19a2-49f1-8286-f62937734b76__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.103.29
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['35253', '35254', '35255', '35256', '35257']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 35253:35253 -p 35254:35254 -p 35255:35255 -p 35256:35256 -p 35257:35257 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=35255 --rest-port=35253 --tcp-port=35254 --discv5-udp-port=35256 --rest-address=0.0.0.0 --nat=extip:172.18.103.29 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=760c206c8a75d6606ae3d2fc56a5adddf8a6c77e60fbedeaa1bc24a29bbfdf39 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=35257 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-L24QEjj4xUxlXV9IV_vqY-uBRMLfDFxj9kNin8rV-1H1GBDAyxqgNTOOHXiZeR0b-1s7VFLrn65RqSVd7oRDrAaNhcCgmlkgnY0gmlwhKwSqqOKbXVsdGlhZGRyc5YACASsEqqjBmLeAAoErBKqowZi390DgnJzhQADAQAAiXNlY3AyNTZrMaED6mbro6vj87BxPWShMFyL9JfEoqijA96XJiHeD8O5DCSDdGNwgmLeg3VkcIJi4IV3YWt1MgU --filternode=/ip4/172.18.170.163/tcp/25310/p2p/16Uiu2HAmURzmvKJQbjssaJMaysSwpsM9wYFzUfUnDvrFexbJaDjy
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.103.29 waku da9f70b8029eaa9c6ccb524ea6789f00607bcf048b24600d3dfe3866483b5d61
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID da9f70b8029e. Setting up logs at ./log/docker/node2_2024-12-04_11-44-47__40c67114-19a2-49f1-8286-f62937734b76__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 35253
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:35253/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:35253/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.103.29/tcp/35254/p2p/16Uiu2HAm2iQQk2HW66L2vaRYeJF7xsH6HhfzwEhSqKGWRYFQKuon","/ip4/172.18.103.29/tcp/35255/ws/p2p/16Uiu2HAm2iQQk2HW66L2vaRYeJF7xsH6HhfzwEhSqKGWRYFQKuon"],"enrUri":"enr:-L24QH9ys9ArGscm6R2j4GIxs2afa4Do9FIBrIoHGac1CpLVL9vb9IrHSsZ-IyEVzP_UWp2UMuoyW5MlEeeYzZn0krkCgmlkgnY0gmlwhKwSZx2KbXVsdGlhZGRyc5YACASsEmcdBom2AAoErBJnHQaJt90DgnJzhQADAQAAiXNlY3AyNTZrMaECbEsTzeGhYxm9ZVFGu7EajjrXlgXhxdpK1oTSntxCoKmDdGNwgom2g3VkcIKJuIV3YWt1MgA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:35253/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.170.163/tcp/25310/p2p/16Uiu2HAmURzmvKJQbjssaJMaysSwpsM9wYFzUfUnDvrFexbJaDjy"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.filter:filter.py:47 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:25309/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:35253/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "658f0873-6435-4707-a2fd-fa82f3699c9c", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"658f0873-6435-4707-a2fd-fa82f3699c9c","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:25309/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d '{"payload": "RmlsdGVyIHdvcmtzISE=", "contentTopic": "/test/1/waku-filter/proto", "timestamp": '$(date +%s%N)', "extraField": "extraValue"}'
[31m[1mERROR   [0m src.node.api_clients.base_client:base_client.py:16 HTTP error occurred: 400 Client Error: Bad Request for url: http://127.0.0.1:25309/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1. Response content: b'Invalid content body, could not decode. Unable to deserialize data'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 01d2cffe58ef
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id da9f70b8029e
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container 01d2cffe58ef. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.