[35mDEBUG   [0m tests.conftest:conftest.py:51 Running fixture setup: test_id
[35mDEBUG   [0m tests.conftest:conftest.py:57 Running test: test_filter_get_message_duplicate_message with id: 2024-12-04_11-44-46__8a7aae2b-6899-462b-9bfb-29514881caea
[35mDEBUG   [0m src.steps.common:common.py:18 Running fixture setup: common_setup
[35mDEBUG   [0m src.steps.filter:filter.py:28 Running fixture setup: filter_setup
[35mDEBUG   [0m src.steps.filter:filter.py:34 Running fixture setup: setup_main_relay_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node1_2024-12-04_11-44-46__8a7aae2b-6899-462b-9bfb-29514881caea__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.22.10
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['1434', '1435', '1436', '1437', '1438']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 1434:1434 -p 1435:1435 -p 1436:1436 -p 1437:1437 -p 1438:1438 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=1436 --rest-port=1434 --tcp-port=1435 --discv5-udp-port=1437 --rest-address=0.0.0.0 --nat=extip:172.18.22.10 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=2aa7afb1c2bbc0e5a5909d308fb0dfaefd382edbe2dd8ac255bc66ef77075bc8 --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=1438 --metrics-logging=true --relay=true --filter=true
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.22.10 waku bd3745de701b7cc6b48fa8047cf53cdc1864989a5f08c2a72aaab90f01316a4b
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID bd3745de701b. Setting up logs at ./log/docker/node1_2024-12-04_11-44-46__8a7aae2b-6899-462b-9bfb-29514881caea__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 1434
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:1434/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:1434/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.22.10/tcp/1435/p2p/16Uiu2HAkwGFmoZEbXKcEwm5WxvG318dcyA6bwFwy7wkvZicNDHUT","/ip4/172.18.22.10/tcp/1436/ws/p2p/16Uiu2HAkwGFmoZEbXKcEwm5WxvG318dcyA6bwFwy7wkvZicNDHUT"],"enrUri":"enr:-L24QB6XTXwHs_-1TTSzFnZ-9rYU3UiZ55IB31brEdTKGxtoTLx-sFIsOI4LsQyMGO5K1V0vjI654evQmfxo6rgKRcUCgmlkgnY0gmlwhKwSFgqKbXVsdGlhZGRyc5YACASsEhYKBgWbAAoErBIWCgYFnN0DgnJzhQADAQAAiXNlY3AyNTZrMaECG03GpAlJRQOIMEWVu8XI7SZ0n-YBP4bEai6diF2dpMiDdGNwggWbg3VkcIIFnYV3YWt1MgU"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[35mDEBUG   [0m src.steps.filter:filter.py:39 Running fixture setup: setup_main_filter_node
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:19 Docker client initialized with image wakuorg/nwaku:latest
[35mDEBUG   [0m src.node.waku_node:waku_node.py:85 WakuNode instance initialized with log path ./log/docker/node2_2024-12-04_11-44-46__8a7aae2b-6899-462b-9bfb-29514881caea__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:89 Starting Node...
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:22 Attempting to create or retrieve network waku
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:25 Network waku already exists
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:108 Generated random external IP 172.18.148.206
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:101 Generated ports ['34108', '34109', '34110', '34111', '34112']
[35mDEBUG   [0m src.node.waku_node:waku_node.py:439 RLN credentials were not set
[32mINFO    [0m src.node.waku_node:waku_node.py:168 RLN credentials not set or credential store not available, starting without RLN
[35mDEBUG   [0m src.node.waku_node:waku_node.py:170 Using volumes []
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:49 docker run -i -t -p 34108:34108 -p 34109:34109 -p 34110:34110 -p 34111:34111 -p 34112:34112 wakuorg/nwaku:latest --listen-address=0.0.0.0 --rest=true --rest-admin=true --websocket-support=true --log-level=TRACE --rest-relay-cache-capacity=100 --websocket-port=34110 --rest-port=34108 --tcp-port=34109 --discv5-udp-port=34111 --rest-address=0.0.0.0 --nat=extip:172.18.148.206 --peer-exchange=true --discv5-discovery=true --cluster-id=3 --nodekey=fbdeada48edc8f3f484eccb2e0a2e4eafbcced89d60277c09888d3a72c6575ba --shard=0 --metrics-server=true --metrics-server-address=0.0.0.0 --metrics-server-port=34112 --metrics-logging=true --relay=false --discv5-bootstrap-node=enr:-L24QB6XTXwHs_-1TTSzFnZ-9rYU3UiZ55IB31brEdTKGxtoTLx-sFIsOI4LsQyMGO5K1V0vjI654evQmfxo6rgKRcUCgmlkgnY0gmlwhKwSFgqKbXVsdGlhZGRyc5YACASsEhYKBgWbAAoErBIWCgYFnN0DgnJzhQADAQAAiXNlY3AyNTZrMaECG03GpAlJRQOIMEWVu8XI7SZ0n-YBP4bEai6diF2dpMiDdGNwggWbg3VkcIIFnYV3YWt1MgU --filternode=/ip4/172.18.22.10/tcp/1435/p2p/16Uiu2HAkwGFmoZEbXKcEwm5WxvG318dcyA6bwFwy7wkvZicNDHUT
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:55 docker network connect --ip 172.18.148.206 waku 9534040d7c494965545c2af38871765bc8c3b22e25e3c6b2567a36bb2154d39a
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:58 Container started with ID 9534040d7c49. Setting up logs at ./log/docker/node2_2024-12-04_11-44-46__8a7aae2b-6899-462b-9bfb-29514881caea__wakuorg_nwaku:latest.log
[35mDEBUG   [0m src.node.waku_node:waku_node.py:182 Started container from image wakuorg/nwaku:latest. REST: 34108
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 1 seconds
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:34108/health" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"nodeHealth":"Ready","protocolsHealth":[]}'
[32mINFO    [0m src.node.waku_node:waku_node.py:282 Node protocols are initialized !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:34108/debug/v1/info" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"listenAddresses":["/ip4/172.18.148.206/tcp/34109/p2p/16Uiu2HAkwrHRv9i57gC7BvMgwCYuHTWzvjJKAK1TrNUuBUR6haHe","/ip4/172.18.148.206/tcp/34110/ws/p2p/16Uiu2HAkwrHRv9i57gC7BvMgwCYuHTWzvjJKAK1TrNUuBUR6haHe"],"enrUri":"enr:-L24QJwIZUt4Sw-zM694nIrzG2MeFT06KZc6QGsV9PwSegJCCn0WI0Ou96Fod9ZgCHnxOybx7F2KBsaZi9e5s8eZ4iwCgmlkgnY0gmlwhKwSlM6KbXVsdGlhZGRyc5YACASsEpTOBoU9AAoErBKUzgaFPt0DgnJzhQADAQAAiXNlY3AyNTZrMaECJAVlrUH_GhPFXTcE9sJW9c_pZbBEHbi6owGveRBVM7mDdGNwgoU9g3VkcIKFP4V3YWt1MgA"}'
[32mINFO    [0m src.node.waku_node:waku_node.py:287 REST service is ready !!
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:34108/admin/v1/peers" -H "Content-Type: application/json" -d '["/ip4/172.18.22.10/tcp/1435/p2p/16Uiu2HAkwGFmoZEbXKcEwm5WxvG318dcyA6bwFwy7wkvZicNDHUT"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.steps.filter:filter.py:47 Running fixture setup: subscribe_main_nodes
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:1434/relay/v1/subscriptions" -H "Content-Type: application/json" -d '["/waku/2/rs/3/1"]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:34108/filter/v2/subscriptions" -H "Content-Type: application/json" -d '{"requestId": "058f6336-d67e-45ad-a79a-7d616328f34d", "contentFilters": ["/test/1/waku-filter/proto"], "pubsubTopic": "/waku/2/rs/3/1"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'{"requestId":"058f6336-d67e-45ad-a79a-7d616328f34d","statusDesc":"OK"}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:1434/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d '{"payload": "RmlsdGVyIHdvcmtzISE=", "contentTopic": "/test/1/waku-filter/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.filter:filter.py:98 Checking that peer NODE_2:wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:34108/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[{"payload":"RmlsdGVyIHdvcmtzISE=","contentTopic":"/test/1/waku-filter/proto","version":0,"timestamp":1733312708180245248,"ephemeral":false}]'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X POST "http://127.0.0.1:1434/relay/v1/messages/%2Fwaku%2F2%2Frs%2F3%2F1" -H "Content-Type: application/json" -d '{"payload": "RmlsdGVyIHdvcmtzISE=", "contentTopic": "/test/1/waku-filter/proto", "timestamp": '$(date +%s%N)'}'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'OK'
[35mDEBUG   [0m src.libs.common:common.py:35 Sleeping for 0.1 seconds
[35mDEBUG   [0m src.steps.filter:filter.py:98 Checking that peer NODE_2:wakuorg/nwaku:latest can find the published message
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:37 curl -v -X GET "http://127.0.0.1:34108/filter/v2/messages/%2Ftest%2F1%2Fwaku-filter%2Fproto" -H "Content-Type: application/json" -d 'None'
[32mINFO    [0m src.node.api_clients.base_client:base_client.py:22 Response status code: 200. Response content: b'[]'
[35mDEBUG   [0m tests.conftest:conftest.py:59 Running fixture teardown: test_setup
[35mDEBUG   [0m tests.conftest:conftest.py:83 Running fixture teardown: close_open_nodes
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id bd3745de701b
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:226 Stopping container with id 9534040d7c49
[31m[1mERROR   [0m src.node.docker_mananger:docker_mananger.py:89 Max retries reached for container bd3745de701b. Exiting log stream.
[35mDEBUG   [0m src.node.waku_node:waku_node.py:233 Container stopped.
[35mDEBUG   [0m tests.conftest:conftest.py:98 Running fixture teardown: check_waku_log_errors
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.
[35mDEBUG   [0m src.node.docker_mananger:docker_mananger.py:144 No errors found in the waku logs.